---
- name: Create App Service Plan
  azure_rm_appserviceplan:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_function_app_plan }}"
    location: "{{ az_region }}"
    sku: S1
    number_of_workers: 1

- name: Create Redis instance
  command: >
    az redis create 
    -l {{ az_region }}
    -n {{ az_project }}Redis
    -g {{ az_resource_group }}
    --sku standard
    --vm-size C0

# Storage Account name must be lowercase
- name: Create Storage account
  azure_rm_storageaccount:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_storage_account }}"
    kind: Storage
    account_type: Standard_LRS

- name: Create Function App
  command: >
    az functionapp create
    --name {{ az_function_app }}
    --resource-group {{ az_resource_group }}
    --storage-account {{ az_storage_account }}
    --plan {{ az_function_app_plan }}